uint32 seconds          # ROS time the message was sent in seconds
uint32 nsec             # ROS time the message was sent, millisecond component
bool rostime            # ROS time if true, Yukon milli() epoch otherwise
float32 voltage_in      # Voltage input to the Yukon
float32 voltage_out     # Voltage input to the Yukon
float32 current         # Voltage input to the Yukon
float32 temperature     # Voltage input to the Yukon