controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_left_shoulder_flappy_joint
      - left_shoulder_flappy_left_shoulder_foreaft_joint
      - left_shoulder_foreaft_left_shoulder_rotate_joint
      - left_shoulder_rotate_left_elbow_joint
      - left_forearm_left_wrist_rotate_joint
      - left_wrist_rotate_left_wrist_pan_joint
      - left_wrist_pan_left_wrist_tilt_joint
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: home